export const MomentaryDataJsx = [
  {
    id: 1,
    img: "/images/coin/btc.png",
    englishName: "BTC",
    PersianName: "Bitcoin",
    tetherPrice: 20072,
    tomanPrice: 937362000,
  },
  {
    id: 2,
    img: "/images/coin/eth.png",
    englishName: "ETH",
    PersianName: "Etherium",
    tetherPrice: 20072,
    tomanPrice: 937362000,
  },
  {
    id: 3,
    img: "/images/coin/bnb.png",
    englishName: "BNB",
    PersianName: "Binance Coin",
    tetherPrice: 274,
    tomanPrice: 12734016,
  },
  {
    id: 4,
    img: "/images/coin/ada.png",
    englishName: "ADA",
    PersianName: "Cardano",
    tetherPrice: 0.064,
    tomanPrice: 3009,
  },
  {
    id: 5,
    img: "/images/coin/cro.png",
    englishName: "CRO",
    PersianName: "Cronos",
    tetherPrice: 20072,
    tomanPrice: 937362000,
  },
  {
    id: 6,
    img: "/images/coin/luna.png",
    englishName: "LUNA",
    PersianName: "LUNA coin",
    tetherPrice: 5.35,
    tomanPrice: 248239,
  },
  {
    id: 7,
    img: "/images/coin/mana.png",
    englishName: "MANA",
    PersianName: "MANA coin",
    tetherPrice: 16.32,
    tomanPrice: 780000,
  },
  {
    id: 8,
    img: "/images/coin/poly.png",
    englishName: "POLY",
    PersianName: "Polymath",
    tetherPrice: 0.31,
    tomanPrice: 14384,
  },
];
